### ISSUE TITLE
wrap_parent doesn't work if register_as is different from dataset

### ISSUE THREAD

**Issue by mmeeoorroo** [rom-rb/rom-repository#18]
I guess the cause by this line

https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/relation_proxy/wrap.rb#L24

It looks up a relation by `register_as` value when create LoadingProxy so It should pass `register_as` value instead of `base_name`, shouldn't it?

Here is my relations and repository:

``` ruby
class ProductsRelation < ROM::Relation[:sql]

end

class CategoriesRelation < ROM::Relation[:sql]

  register_as :categories_relation
  dataset :categories

  primary_key :id

end


class ProductRepository < ROM::Repository::Base
  relations :products, :categories

  def with_category
    products.wrap_parent(category: categories)
  end
end


# this call raises error
repo.with_category

NoMethodError: undefined method `name' for nil:NilClass
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-sql-0.7.0/lib/rom/plugins/relation/sql/auto_wrap.rb:35:in `for_wrap'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-support-1.0.0/lib/rom/support/auto_curry.rb:30:in `call'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-support-1.0.0/lib/rom/support/auto_curry.rb:30:in `block in auto_curry'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-support-1.0.0/lib/rom/support/auto_curry.rb:30:in `call'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-support-1.0.0/lib/rom/support/auto_curry.rb:30:in `block in auto_curry'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-repository-0.2.0/lib/rom/repository/loading_proxy/wrap.rb:27:in `block in wrap'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-repository-0.2.0/lib/rom/repository/loading_proxy/wrap.rb:23:in `each'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-repository-0.2.0/lib/rom/repository/loading_proxy/wrap.rb:23:in `reduce'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-repository-0.2.0/lib/rom/repository/loading_proxy/wrap.rb:23:in `wrap'
    from /home/dung/.rvm/gems/ruby-2.2.4@cai-kho/gems/rom-repository-0.2.0/lib/rom/repository/loading_proxy/wrap.rb:42:in `wrap_parent'
```

**Comment by solnic** [comment]
This is a dup of https://github.com/rom-rb/rom-sql/issues/42 I'll fix it in next release of rom-sql
