### ISSUE TITLE
Command registration attempts to fetch relation using dataset name, not relation name  

### ISSUE THREAD

**Issue by daniels** [rom-rb/rom-repository#30]
When the registered name of a relation differs from the name of the dataset, the relation isn't found during command registration, since the name sent to `register_command` is the `base_name` from the ast, not the name of the relation.

I have a failing spec for this (and a passing spec for when the relation and dataset are identically named), but I'm not sure how/if I should submit it as a pull request as it lives in a separate file from related spec, due to the need to setup the relation names differently. I'll just paste it here for now:

``` ruby
RSpec.describe 'ROM repository' do

  include_context 'database'

  shared_context 'repo with users' do

    before do
      table_name = @table_name
      configuration.relation(@relation_name) do
        dataset table_name

        schema(dataset, infer: true)
      end
    end

    let(:repo) { repo_class.new(rom) }

    let(:repo_class) {
      Class.new(ROM::Repository[@relation_name]) do
        commands :create
      end
    }

  end

  shared_examples 'creating a user' do
    it 'can create a user' do
      expect(repo.create(name: "Josh").name).to eq('Josh')
    end
  end

  context 'with matching relation and dataset names' do

    before do
      @table_name    = :users
      @relation_name = @table_name
    end

    include_context 'repo with users'
    include_examples 'creating a user'
  end

  context 'with non-matching relation and dataset names' do

    before do
      @table_name    = :users
      @relation_name = :something_different
    end

    include_context 'repo with users'
    include_examples 'creating a user'
  end

end
```

The result of running the spec:

```
Randomized with seed 62448
F.

Failures:

  1) ROM repository with non-matching relation and dataset names can create a user
     Failure/Error: relation = container.relations[name]

     ROM::Registry::ElementNotFoundError:
       :users doesn't exist in ROM::RelationRegistry registry
     Shared Example Group: "creating a user" called from ./spec/integration/command_with_custom_dataset_name_spec.rb:51
     # ./vendor/bundle/bundler/gems/rom-support-31085bb9a02a/lib/rom/support/registry.rb:33:in `block in fetch'
     # ./vendor/bundle/bundler/gems/rom-support-31085bb9a02a/lib/rom/support/registry.rb:30:in `fetch'
     # ./vendor/bundle/bundler/gems/rom-support-31085bb9a02a/lib/rom/support/registry.rb:30:in `fetch'
     # ./lib/rom/repository/command_compiler.rb:89:in `block in register_command'
     # ./vendor/bundle/bundler/gems/rom-9b30e3b516be/lib/rom/commands/class_interface.rb:73:in `create_class'
     # ./lib/rom/repository/command_compiler.rb:83:in `register_command'
     # ./lib/rom/repository/command_compiler.rb:65:in `visit_relation'
     # ./lib/rom/repository/command_compiler.rb:50:in `visit'
     # ./lib/rom/repository/command_compiler.rb:19:in `block in []'
     # ./vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:133:in `block in fetch_or_store'
     # ./vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:122:in `fetch'
     # ./vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:132:in `fetch_or_store'
     # ./lib/rom/repository/command_compiler.rb:12:in `[]'
     # ./lib/rom/repository.rb:96:in `compile_command'
     # ./lib/rom/repository.rb:69:in `block in command'
     # ./vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:133:in `block in fetch_or_store'
     # ./vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:122:in `fetch'
     # ./vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:132:in `fetch_or_store'
     # ./lib/rom/repository.rb:68:in `command'
     # ./lib/rom/repository/class_interface.rb:77:in `block in define_command_method'
     # ./spec/integration/command_with_custom_dataset_name_spec.rb:28:in `block (3 levels) in <top (required)>'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /Users/dan/.gem/ruby/2.2.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'

Finished in 0.14597 seconds (files took 0.35833 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/integration/command_with_custom_dataset_name_spec.rb[1:2:1] # ROM repository with non-matching relation and dataset names can create a user

Randomized with seed 62448
```

**Comment by flash-gordon** [comment]
@daniels I took your code and now it works! 🎉

**Comment by daniels** [comment]
Yes, thank you so much! 🙇 This will let me take part of the new command interface and also make life with a legacy DB easier all over the place! 😃
