### ISSUE TITLE
Aggregate write doesn't work with belongs_to

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-repository#45]
Here is test case:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rom'
  gem 'minitest'
  gem 'rom-sql'
  gem 'rom-repository'
  gem 'sqlite3'
end

require 'minitest/autorun'
require 'rom-repository'

$rom = ROM.container(:sql, 'sqlite::memory') do |conf|
  conf.default.create_table(:users) do
    primary_key :id
    column :name, String, null: false
    foreign_key :address_id, :addresses
  end

  conf.default.create_table(:addresses) do
    primary_key :id
    column :city, String, null: false
    column :country, String, null: false
  end

  conf.relation(:users) do
    schema(infer: true) do
      associations do
        belongs_to :addresses
      end
    end
  end

  conf.relation(:addresses) do
    schema(infer: true)
  end
end

class UsersRepo < ROM::Repository[:users]
  relations :addresses

  def create_with_address(user)
    command(:create, aggregate(:addresses)).call(user)
  end
end

class BugTest < Minitest::Test
  def test_aggregated_create
    repo = UsersRepo.new($rom)
    repo.create_with_address(
      name: 'User', address: {city: 'Kyiv', country: 'Ukraine'}
    )
  end
end
```

Test case raises exception `NoMethodError: undefined method '>' for nil:NilClass`

<details>

```
  1) Error:
BugTest#test_aggregated_create:
NoMethodError: undefined method `>' for nil:NilClass
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-logic-0.4.0/lib/dry/logic/predicates.rb:103:in `gt?'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-logic-0.4.0/lib/dry/logic/rule.rb:51:in `[]'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-logic-0.4.0/lib/dry/logic/rule.rb:51:in `[]'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-logic-0.4.0/lib/dry/logic/rule.rb:47:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/constrained.rb:38:in `try'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/constrained.rb:26:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/hash/schema.rb:75:in `block in coerce'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/hash/schema.rb:88:in `block in resolve'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/hash/schema.rb:86:in `each'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/hash/schema.rb:86:in `resolve'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/hash/schema.rb:73:in `coerce'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/hash/schema.rb:27:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.9.3/lib/dry/types/constructor.rb:39:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/create.rb:24:in `block in execute'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/create.rb:60:in `block in with_input_tuples'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/create.rb:60:in `map'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/create.rb:60:in `each'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/create.rb:60:in `with_input_tuples'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/create.rb:23:in `execute'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/plugin/associates.rb:52:in `execute'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/command.rb:110:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.1/lib/rom/sql/commands/error_wrapper.rb:12:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/commands/lazy/create.rb:17:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/commands/graph.rb:64:in `block in call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/commands/graph.rb:61:in `map'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/commands/graph.rb:61:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/commands/composite.rb:18:in `call'
    /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-repository-0.3.1/lib/rom/repository/command_proxy.rb:14:in `call'
    rom_repo_aggregate_belongs_to.rb:50:in `create_with_address'
    rom_repo_aggregate_belongs_to.rb:57:in `test_aggregated_create'
```

</details>

It's because create command adds `id: nil` to address tuple somewhere in middle of the process, and it fails `gt?` predicate for primary key.

If `:addresses` doesn't have `schema(infer: true)`, if doesn't fail, but doesn't work as well: result is

    #<ROM::Struct[User] id=1 name="User" address_id=nil addresses=nil>

Another question is for `dry-logic`, should `Types::Int.constrained(gt: 0)[nil]` fails with `NoMethodError: undefined method '>' for nil:NilClass` and be unrescued? This makes debugging very hard.

**Comment by solnic** [comment]
This was fixed (using latest master rom/repo/sql):

``` ruby
rom-rb/rom-repository (master«) % be ruby tmp/repros/45.rb
Run options: --seed 27201

# Running:

.

Finished in 0.008942s, 111.8318 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```
