### ISSUE TITLE
NoMethodError when using `#node` and `map_with(auto_map: true)`

### ISSUE THREAD

**Issue by backus** [rom-rb/rom-repository#78]
Reproduction:

```ruby
# frozen_string_literal: true

require 'rom'
require 'rom/sql'
require 'rom/repository'
require 'rom/repository/version'

require 'logger'

ROM::VERSION             # => "3.1.0"
ROM::SQL::VERSION        # => "1.2.1"
ROM::Repository::VERSION # => "1.3.0"

class FoosRepo < ROM::Repository[:foos]
  relations(:bars)

  def with_baz
    aggregate(:bar)
      .node(:bar) { |relation| relation.as(:entity, auto_map: true) }
      .to_a
  end
end

rom = ROM.container(:sql, 'sqlite::memory') do |config|
  config.default.create_table(:foos) do
    primary_key :id
  end

  config.default.create_table(:bars) do
    column :id, Integer
    foreign_key :foo_id, :foos
  end

  config.relation(:foos) do
    schema(:foos) do
      attribute :id, ROM::Types::Int
      primary_key :id

      associations do
        has_one :bars, as: :bar, foreign_key: :foobar_id
      end
    end
  end

  config.relation(:bars) do
    schema(infer: true)
  end
end

p FoosRepo.new(rom).with_baz

# ~> /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-mapper-0.5.0/lib/rom/header.rb:56:in `coerce': undefined method `each_with_object' for :bar:Symbol (NoMethodError)
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/header_builder.rb:15:in `call'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/mapper_builder.rb:18:in `block in call'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/dry-core-0.2.4/lib/dry/core/cache.rb:49:in `fetch_or_store'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/dry-core-0.2.4/lib/dry/core/cache.rb:61:in `fetch_or_store'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/mapper_builder.rb:18:in `call'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/relation_proxy.rb:159:in `mapper'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/relation_proxy.rb:95:in `map_with'
# ~>  from -:19:in `block in with_baz'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/relation_proxy.rb:128:in `block in node'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/relation_proxy.rb:125:in `map'
# ~>  from /Users/johnbackus/.gem/ruby/2.4.0/gems/rom-repository-1.3.0/lib/rom/repository/relation_proxy.rb:125:in `node'
# ~>  from -:19:in `with_baz'
# ~>  from -:50:in `<main>'
```

**Comment by mrship** [comment]
I came across this via a comment in gitter chat with @flash-gordon. I too would like to be able to apply a mapper to the nested data struct, as described above.

@backus did you find a workaround?

**Comment by backus** [comment]
@mrship I think I just defined a custom mapper instead

**Comment by mrship** [comment]
Ok, thanks. I ended up doing the the same as a workaround.

**Comment by flash-gordon** [comment]
@backus I guess I fixed this, could check out this PR https://github.com/rom-rb/rom-repository/pull/84 and say if it works for you?

**Comment by backus** [comment]
@flash-gordon unfortunately I seem to get an error when using #84:

```ruby
# frozen_string_literal: true

require 'rom'
require 'rom/sql'
require 'rom/repository'
require 'rom/repository/version'

require 'logger'

ROM::VERSION             # => "3.1.0"
ROM::SQL::VERSION        # => "1.2.1"
ROM::Repository::VERSION # => "1.3.0"

class FoosRepo < ROM::Repository[:foos]
  relations(:bars)

  def with_baz
    aggregate(:bar)
      .node(:bar) { |relation| relation.as(:entity, auto_map: true) }
      .to_a
  end
end

rom = ROM.container(:sql, 'sqlite::memory') do |config|
  config.default.create_table(:foos) do
    primary_key :id
  end

  config.default.create_table(:bars) do
    column :id, Integer
    foreign_key :foo_id, :foos
  end

  config.relation(:foos) do
    schema(:foos) do
      attribute :id, ROM::Types::Int
      primary_key :id

      associations do
        has_one :bars, as: :bar, foreign_key: :foobar_id
      end
    end
  end

  config.relation(:bars) do
    schema(infer: true)
  end
end

p FoosRepo.new(rom).with_baz

# ~> /Users/johnbackus/.gem/ruby/2.3.1/bundler/gems/rom-repository-faaf24815b06/lib/rom/repository.rb:91:in `block in <class:Repository>': wrong number of arguments (given 1, expected 0) (ArgumentError)
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/plugins/default_proc.rb:13:in `instance_eval'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/plugins/default_proc.rb:13:in `block in call'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/builder.rb:94:in `instance_eval'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/builder.rb:94:in `block (2 levels) in reload_callback'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/builder.rb:94:in `each'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/builder.rb:94:in `block in reload_callback'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/builder.rb:84:in `__initialize__'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/gems/dry-initializer-0.11.0/lib/dry/initializer/mixin.rb:49:in `initialize'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/bundler/gems/rom-repository-faaf24815b06/lib/rom/repository.rb:112:in `initialize'
# ~>  from /Users/johnbackus/.gem/ruby/2.3.1/bundler/gems/rom-repository-faaf24815b06/lib/rom/repository/root.rb:61:in `initialize'
# ~>  from -:50:in `new'
# ~>  from -:50:in `<main>'
```

Gemfile used to run this:

```ruby
source 'https://rubygems.org'

gem 'rom', '~> 3.1.0'
gem 'rom-repository', github: 'rom-rb/rom-repository', branch: 'using-mapper-inside-node'
gem 'rom-sql', '~> 1.2.1'
gem 'pg'
gem 'sqlite3'

gem 'pry'
gem 'dry-types'
gem 'dry-struct'

group :tools do
  gem 'rcodetools'
end
```

**Comment by flash-gordon** [comment]
Could you use rom from master?

**Comment by backus** [comment]
👍 when rom, rom-repository, rom-sql are all on master

**Comment by flash-gordon** [comment]
Great, I'll push a new version later this week, tomorrowish
