### ISSUE TITLE
Cannot use mapper unless register_as is provided

### ISSUE THREAD

**Issue by blelump** [rom-rb/rom-repository#83]
Hi !

I've registered a mapper with setup DSL:
```ruby
require 'rom-repository'
require 'rom-sql'
require 'ostruct'

config = ROM::Configuration.new(:sql, 'sqlite::memory')

config.gateways[:default].connection.create_table(:tags) do
  primary_key :id
  column :taggable_id, Integer
  column :name, String
end

config.relation(:tags) do
  schema(infer: true)
end

config.mappers do
  define(:tag_mapper) do
    model OpenStruct
    relation :tags

    attribute :name_blebla, from: :name
  end
end

class TagRepo < ROM::Repository[:tags]
  commands :create
end

rom = ROM.container(config)

tag_repo = TagRepo.new(rom)

tag_repo.create(name: 'red')
tag_repo.create(name: 'blue')

p tag_repo.tags.as(:tag_mapper).to_a
```

It raises with:
```
from gems/rom-3.1.0/lib/rom/mapper_registry.rb:13:in `block in []': tag_mapper (ROM::MapperMissingError)
from gems/rom-3.1.0/lib/rom/mapper_registry.rb:13:in `fetch'
from gems/rom-3.1.0/lib/rom/mapper_registry.rb:13:in `[]'
from gems/rom-repository-1.2.0/lib/rom/repository/relation_proxy.rb:98:in `block in map_with'
from gems/rom-repository-1.2.0/lib/rom/repository/relation_proxy.rb:98:in `each'
from gems/rom-repository-1.2.0/lib/rom/repository/relation_proxy.rb:98:in `reduce'
from gems/rom-repository-1.2.0/lib/rom/repository/relation_proxy.rb:98:in `map_with'
```

However, when mapper is defined with `register_as`, ie:
```ruby
define(:tag_mapper) do
    model OpenStruct
    relation :tags
    register_as :tag_mapper

    attribute :name_blebla, from: :name
  end
```
it works fine. It also works well for custom mapper class:
```ruby
class TagMapper < ROM::Mapper
  model OpenStruct
  relation :tags
  register_as :tag_mapper

  attribute :name_blebla, from: :name
end
config.register_mapper(TagMapper)
```
but when I'll use a constant instead of a symbol while reading, ie:
```ruby
tag_repo.tags.as(TagMapper).to_a
```

it dies with:

```
from gems/rom-mapper-0.5.0/lib/rom/processor/transproc.rb:85:in `initialize': undefined method `model' for {:id=>1, :taggable_id=>nil, :name=>"red"}:Hash (NoMethodError)
from gems/rom-mapper-0.5.0/lib/rom/processor/transproc.rb:78:in `new'
from gems/rom-mapper-0.5.0/lib/rom/processor/transproc.rb:78:in `build'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:79:in `block in initialize'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:78:in `map'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:78:in `initialize'
from gems/transproc-1.0.2/lib/transproc/class.rb:30:in `new'
from gems/transproc-1.0.2/lib/transproc/class.rb:30:in `constructor_inject'
from gems/transproc-1.0.2/lib/transproc/function.rb:47:in `call'
from gems/transproc-1.0.2/lib/transproc/function.rb:47:in `call'
from gems/transproc-1.0.2/lib/transproc/array.rb:42:in `block in map_array'
from gems/transproc-1.0.2/lib/transproc/array.rb:42:in `map'
from gems/transproc-1.0.2/lib/transproc/array.rb:42:in `map_array'
from gems/transproc-1.0.2/lib/transproc/function.rb:47:in `call'
from gems/transproc-1.0.2/lib/transproc/function.rb:47:in `call'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `block in call'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `each'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `reduce'
from gems/rom-mapper-0.5.0/lib/rom/mapper.rb:95:in `call'
from gems/rom-3.1.0/lib/rom/relation/composite.rb:22:in `call'
from gems/rom-repository-1.2.0/lib/rom/repository/relation_proxy.rb:51:in `call'
from gems/rom-3.1.0/lib/rom/relation/materializable.rb:20:in `to_a'
```

According to the [docs][1], if a constant is given, it is resolved as an entity, whereas if a symbol is given, it looks for a mapper. Perhaps it would be a good idea to make it more explicit? For instance, I would consider `#map_with` as a something that maps the input and expects a mapper, whereas `#as` tells me, that no extra transformations are going to be performed and the result is single entity or a collection of them:

```ruby
tag_repo.tags.map_with(Mapper)
tag_repo.tags.map_with(:mapper)

tag_repo.tags.as(Tag)
tag_repo.tags.as(:tag)
```

What do you think?

[1]: https://github.com/rom-rb/rom-repository/blob/83bcd7310c6d6f0924d51db6d09283d408affa9a/lib/rom/repository/relation_proxy.rb#L54

**Comment by flash-gordon** [comment]
For me it looks like a reasonable improvement and can happen in 4.0. 
@solnic wdyt?
Minor notice that `map_with` should always receive a symbol and `as` should receive a class

**Comment by solnic** [comment]
I'd like to address this finally. My proposal is kinda radical though:

- deprecate current `Relation#as` behavior in favor of using this method for aliasing relations (this will be inline with aliasing attributes and relation names)
- add `Relation#map_to(ModelName)`
- tweak `Relation#map_with` so that it accepts a list of mapper identifiers exclusively

**Comment by flash-gordon** [comment]
+1 for changing the behavior of `Relation#as`

**Comment by solnic** [comment]
@flash-gordon fantastic, I'll do it then

**Comment by solnic** [comment]
oh btw and this issue actually does describe a bug because mapper dsl in configuration doesn't set `register_as` so it always defaults to relation name, simple fix though.

**Comment by solnic** [comment]
I reported rom-rb/rom#425 so closing this one
