### ISSUE TITLE
Bug: aggregate doesn't work with relations with different dataset

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-repository#85]
If a relation has different dataset name, aggregation with this relation doesn't work.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rom'
  gem 'rom-sql'
  gem 'rom-repository'
  gem 'sqlite3'
  gem 'rspec'
  gem 'pry'
end

require 'rspec/autorun'

describe ROM::Repository do
  let(:rom) { ROM.container(configuration) }
  let(:users_table) { :users }
  let(:configuration) do
    users_table_ = users_table
    ROM::Configuration.new(:sql, 'sqlite::memory').tap do |config|
      config.default.create_table(users_table_) do
        primary_key :id
        column :name, String, null: false
      end

      config.default.create_table(:posts) do
        primary_key :id
        foreign_key :user_id, users_table_, null: false
        column :title, String, null: false
      end

      config.relation(:users) do
        dataset users_table_
        schema(infer: true)
      end

      config.relation(:posts) do
        schema(infer: true) do
          associations do
            belongs_to :user, foreign_key: :user_id
          end
        end
      end
    end
  end

  let(:repo) do
    Class.new(ROM::Repository[:posts]) do
      relations :users

      def all
        aggregate(:user).to_a
      end
    end.new(rom)
  end

  before { create_post(title: 'post_title', user_name: 'Sergiy') }

  it 'fetches 1 record' do
    expect(repo.all.count).to eq 1
  end

  let(:first) { repo.all.first }

  it 'builds Post struct' do
    expect(first.title).to eq 'post_title'
    expect(first.user.name).to eq 'Sergiy'
  end

  context 'with different table name' do
    let(:users_table) { :users_table }

    it 'still builds Post struct' do
      expect(first.title).to eq 'post_title'
      expect(first.user.name).to eq 'Sergiy'
    end
  end

  def create_post(attrs)
    user_id = rom.relations[:users].insert(name: attrs.fetch(:user_name))
    rom.relations[:posts].insert(title: attrs.fetch(:title), user_id: user_id)
  end
end
```

```
Failures:

  1) ROM::Repository with different table name still builds Post struct
     Failure/Error: aggregate(:user).to_a

     Sequel::DatabaseError:
       SQLite3::SQLException: no such column: users.id
     # rom_dataset_bug.rb:57:in `all'
     # rom_dataset_bug.rb:68:in `block (2 levels) in <main>'
     # rom_dataset_bug.rb:80:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # SQLite3::SQLException:
     #   no such column: users.id
     #   rom_dataset_bug.rb:57:in `all'
```
The error is caused because aggregate second query uses wrong table name in inner join query (another question, why it does inner join in that query).

```
SELECT `users_table`.`id`, `users_table`.`name`, `posts`.`id` AS 'post_id' FROM `users_table` INNER JOIN `posts` ON (`posts`.`user_id` = `users`.`id`) WHERE (`posts`.`id` IN (1)) ORDER BY `users_table`.`id`
```

Should be

```
SELECT `users_table`.`id`, `users_table`.`name`, `posts`.`id` AS 'post_id' FROM `users_table` INNER JOIN `posts` ON (`posts`.`user_id` = `users_table`.`id`) WHERE (`posts`.`id` IN (1)) ORDER BY `users_table`.`id`
```

P.S. How do you like such type of bug reports? Do they contain all necessary information?

**Comment by Kukunin** [comment]
It has the same error for `combine_parents` method as well

**Comment by solnic** [comment]
This is fixed in rom-rb/rom master
