### ISSUE TITLE
uuid as primary key and inferring associations

### ISSUE THREAD

**Issue by glenndavy** [rom-rb/rom-repository#86]
Hi all, bouncing over here from [discuss](https://discuss.rom-rb.org/t/uuid-and-primary-key-inference-on-associations/144).

What I'm hoping to do is simply use UUIDs as my PK's in PG.

First here's a simple (if verbose) pre-uuid experiment that works:

```ruby
#!/usr/bin/env ruby
require 'bundler/setup'
require 'rom-sql'
require 'rom-repository'

module Relations

  class Series < ROM::Relation[:sql]
    schema(:series) do
      attribute :id, Types::Int
      attribute :database_rp, Types::String
      attribute :measurement, Types::String
      attribute :tag_set, Types::String

      primary_key :id

      associations do
        has_many :archives
      end
    end

    def by_id(id)
      where(id: id)
    end

    def by_series(measurement:, tag_set: )
      # A series definition is
      where(measurement: measurement).where(tag_set: tag_set)
    end
  end

  class Archives < ROM::Relation[:sql]
    schema(:archives) do
      attribute :id, Types::Int
      attribute :series_id, Types::String
      attribute :date_from, Types::Date
      attribute :date_to, Types::Date
      attribute :status, Types::String
      associations do
        belongs_to :series
      end
    end
  end
end

module Repositories

  class Series < ROM::Repository[:series]
    
    commands :create
    
    def [](id)
      series.by_id(id).one!
    end

    def from_definition(measurement:, tag_set:)
      series.by_series(measurement: measurement, tag_set:  tag_set)
    end
  end

  class Archives < ROM::Repository[:archives]
    commands :create
  end
end

configuration = ROM::Configuration.new(:sql, 'postgres://localhost/rom-test')
configuration.register_relation Relations::Series
configuration.register_relation Relations::Archives
container = ROM.container(configuration)

gateway = container.gateways[:default]

migration = gateway.migration do
  change do
    create_table :series do
      primary_key :id
      String :database_rp, null: false
      String :measurement, null: false
      String :tag_set, null: false
    end
    
    create_table :archives do
      primary_key :id
      foreign_key :series_id, null: false
      Date :date_from
      Date :date_to
      String :status, null: false, default: 'Not started'
    end
  end
end

migration.apply(gateway.connection, :up)

series_repo = Repositories::Series.new(container)
archives_repo = Repositories::Archives.new(container)

first_series = series_repo.create(database_rp: 'test.default', measurement: 'cpu', tag_set: 'cpu=cpu0,instance_id=i-1234,role=web')
puts first_series

first_archive_cs = archives_repo.changeset(date_from: Date.today, date_to: Date.today).associate(first_series)
archives_repo.create(first_archive_cs)
```

Here's my attempt to do the same thing using the same code, with UUID which chokes on ```.associate```

```ruby
#!/usr/bin/env ruby
require 'bundler/setup'
require 'rom-sql'
require 'rom-repository'
require 'securerandom'
require 'rom/sql/extensions/postgres/types'

module Relations

  class Series < ROM::Relation[:sql]
    schema(:series) do
      attribute :id, Types::PG::UUID
      attribute :database_rp, Types::String
      attribute :measurement, Types::String
      attribute :tag_set, Types::String

      associations do
        has_many :archives
      end
    end

    def by_id(id)
      where(id: id)
    end

    def by_series(measurement:, tag_set: )
      # A series definition is
      where(measurement: measurement).where(tag_set: tag_set)
    end
  end

  class Archives < ROM::Relation[:sql]
    schema(:archives) do
      attribute :id, Types::PG::UUID
      attribute :series_id, Types::String
      attribute :date_from, Types::Date
      attribute :date_to, Types::Date
      attribute :status, Types::String
      associations do
        belongs_to :series
      end
    end
  end
end

module Repositories

  class Series < ROM::Repository[:series]
    
    commands :create
    
    def [](id)
      series.by_id(id).one!
    end

    def from_definition(measurement:, tag_set:)
      series.by_series(measurement: measurement, tag_set:  tag_set)
    end
  end

  class Archives < ROM::Repository[:archives]
    commands :create
  end
end

configuration = ROM::Configuration.new(:sql, 'postgres://localhost/rom-test')
configuration.register_relation Relations::Series
configuration.register_relation Relations::Archives
container = ROM.container(configuration)

gateway = container.gateways[:default]

migration = gateway.migration do
  change do
    run 'CREATE EXTENSION "uuid-ossp"'
    create_table :series do
      uuid :id, default: Sequel.function(:uuid_generate_v4), primary_key: true
      String :database_rp, null: false
      String :measurement, null: false
      String :tag_set, null: false
    end
    
    create_table :archive do
      uuid :id, default: Sequel.function(:uuid_generate_v4), primary_key: true
      foreign_key :series_id, null: false
      Date :date_from
      Date :date_to
      String :status, null: false, default: 'Not started'
    end
  end
end

migration.apply(gateway.connection, :up)

series_repo = Repositories::Series.new(container)
archives_repo = Repositories::Archives.new(container)

first_series = series_repo.create(database_rp: 'test.default', measurement: 'cpu', tag_set: 'cpu=cpu0,instance_id=i-1234,role=web')
puts first_series

first_archive_cs = archives_repo.changeset(date_from: Date.today, date_to: Date.today).associate(first_series)
archives_repo.create(first_archive_cs)
```

It occurred to me to declare that ```primary_key: id``` as I did in the top example, but this seems to need id to be an Int.

Thanks for reading and for any help you can give.

**Comment by solnic** [comment]
Thanks for reporting this. It needs a closer look though so I can't immediately tell you what's going on. Could you also add some backtrace to the description?

**Comment by glenndavy** [comment]
Hey thanks Solnic,

Backtrace below:

```ruby
/Users/glenn/.gem/ruby/2.3.3/gems/rom-repository-1.3.1/lib/rom/repository/changeset/associated.rb:36:in `infer_assoc_name': can't infer association name for #<ROM::Struct[Series]:0x7fc8be131558> (ArgumentError)
from /Users/glenn/.gem/ruby/2.3.3/gems/rom-repository-1.3.1/lib/rom/repository/changeset/stateful.rb:188:in `associate'
from ./run-with-uuid.rb:106:in `<main>'
```

**Comment by solnic** [comment]
@glenndavy ok for now just pass in assoc name explicitly so `associate(series, :series)`. I'll look into why it can't infer in your case. Another thing to try is to define your attribute in the schema like that:

``` ruby
attribute :id, Types::PG::UUID.meta(primary_key: true)
```

**Comment by glenndavy** [comment]
Hi @solnic,

Thanks for that tip. What I ended up finding was I needed this as suggested:
```ruby
attribute :id, Types::PG::UUID.meta(primary_key: true)
```
and to change this:

```ruby
foreign_key :series_id, null: false
```
to this:

```ruby
 uuid :series_id, null: false
```

**Comment by solnic** [comment]
This works just fine (at least on master) https://gist.github.com/solnic/25f217393c5554a3c0ef49f1c948470b
